# Generated by Django 4.0.5 on 2022-07-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
