# Generated by Django 4.0.5 on 2022-07-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0002_rename_customer_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hairdresser',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id']},
        ),
    ]
