# Generated by Django 4.0.5 on 2022-07-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0002_rename_haidresser_hairdresser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='haidresser',
            new_name='hairdresser',
        ),
    ]
